services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres16:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}