name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn verify -Pintegration-tests

      - name: Package the application
        run: mvn package -DskipTests

      - name: Build Docker image
        env:
          DB_USER: $DB_USER
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: $DB_URL
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: docker build -t simple-bank-account:v1 .

      - name: Deploy to Somewhere # Need to set up where to deploy.
        run: |
          echo "Deployed"
          docker image ls
          
